Table User {
	id Int
	email String
	name String
	posts Post
	profile Profile
	role Role
}

Table Profile {
	id Int
	bio String
	user User
	userId Int
}

Table Post {
	id Int
	title String
	content String
	published Boolean
	author User
	authorId Int
}

Enum Role {
	ADMIN
	USER
}

Ref: Profile.userId - User.id

Ref: Post.authorId > User.id